username: ubuntu

#openjdk vars
openjdk_version: 8
openjdk_package_name: "openjdk-{{openjdk_version}}-jdk"

# postgresql / postgis
ubuntu_release_codename: "bionic"
pg_repo_str: "deb http://apt.postgresql.org/pub/repos/apt/ {{ubuntu_release_codename}}-pgdg main"
pg_repo_key_url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
pg_version: "12"
pgis_version: "2.5"
pg_package: "postgresql-{{pg_version}}"
pgis: "postgresql-{{pg_version}}-postgis-{{pgis_version}}"

# datadir repo
git_username: Alessandro Parma
git_email: alessa.parma@gmail.com
repo_name: geoserver-datadir
repo_url: "git@gitlab.com:alessandro.parma/{{repo_name}}.git"
repo_download_path: "/home/{{username}}/{{repo_name}}"
repo_des: "/var/lib/tomcat8/{{repo_name}}"

source_key: credentials/id_rsa
dest_key: "/home/{{username}}/.ssh/id_rsa"

geoserver_version_number: 2.16.x
geoserver_version: "geoserver-{{geoserver_version_number}}-latest-war"
geoserver_url: "https://build.geoserver.org/geoserver/{{geoserver_version_number}}/{{geoserver_version}}.zip"

tomcat_user: tomcat
tomcat_group: tomcat

tomcat_install_dir: /var/lib/tomcat8

tomcat_java_home: /usr/lib/jvm/jre
tomcat_service_name: tomcat

java_opts: |
  'JAVA_OPTS="-Xms1024m -Xmx1024m 
  -XX:+UseParallelGC -XX:+UseParallelOldGC 
  -DGEOSERVER_DATA_DIR={{repo_download_path}} 
  -DGEOWEBCACHE_CONFIG_DIR={{repo_download_path}}/gwc 
  -DGEOSERVER_LOG_LOCATION={{repo_download_path}}/logs/dir/geoserver.log 
  -DGEOSERVER_NODE_OPTS=id:<color> 
  -DALLOW_ENV_PARAMETRIZATION=true 
  -Xbootclasspath/a:/var/lib/tomcat8/webapps/geoserver/WEB-INF/lib/marlin-0.9.3.jar 
  -Xbootclasspath/p:/var/lib/tomcat8/webapps/dir/geoserver/WEB-INF/lib/marlin-0.9.3.jar 
  -DGEOSERVER_AUDIT_PATH={{repo_download_path}}/audits 
  -DPROXY_BASE_URL=http://publichostname/geoserver"'
