---
- name: Get geoserver 1 webpage
  uri:
    timeout: 50
    url: "{{geoserver1_url}}"
    return_content: yes
  register: this
  failed_when: "'GeoServer instance' not in this.content"
  delegate_to: 127.0.0.1

- name: Get geoserver 2 webpage
  uri:
    timeout: 50
    url: "{{geoserver2_url}}"
    return_content: yes
  register: webpage
  failed_when: "'GeoServer instance' not in webpage.content"
  delegate_to: 127.0.0.1

- name: Get geoserver from the loadbalancer
  uri:
    timeout: 50
    url: "{{loadbalancer_url}}"
    return_content: yes
  register: this
  failed_when: "'GeoServer instance' not in this.content"
  delegate_to: 127.0.0.1
