---
- name: Get geoserver 1 webpage
  uri:
    timeout: 50
    url: "{{geoserver1_url}}"
    return_content: yes
  register: webpage
  failed_when: "'GeoServer instance' not in webpage.content"

- name: Get geoserver 2 webpage
  uri:
    timeout: 50
    url: "{{geoserver2_url}}"
    return_content: yes
  register: webpage
  failed_when: "'GeoServer instance' not in webpage.content"

- name: Get geoserver from the ansible machine
  uri:
    timeout: 50
    url: "{{ansible_machine_url}}"
    return_content: yes
  register: webpage
  failed_when: "'GeoServer instance' not in webpage.content"
