---
- name: Ensure HAProxy is installed.
  become: yes
  apt:
    name: haproxy
    state: present

- name: Copy HAProxy configuration in place.
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644

- name: ensure HAProxy is enabled
  service:
    name: haproxy
    enabled: yes

- name: Ensure HAProxy is running
  service:
    name: haproxy
    state: restarted

- name: Prune logs
  cron:
    name: "prune HAProxy logs"
    minute: "0"
    hour: "0"
    job: "/usr/bin/find /var/log/ -type f -mtime +{{logs_retention}} -delete"


- name: Smoke testing loadbalancer
  uri:
    timeout: "{{timeout_seconds}}"
    url: "{{loadbalancer_url}}"
    return_content: yes
  register: this
  failed_when: "'GeoServer instance' not in this.content"
