---
- name: Ensure HAProxy is installed.
  become: yes
  apt:
    name: haproxy
    state: present

- name: Copy HAProxy configuration in place.
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644

- name: ensure HAProxy is enabled
  service:
    name: haproxy
    enabled: yes

- name: Ensure HAProxy is running
  service:
    name: haproxy
    state: restarted
